[[redirects]]
  from = "/add-note"
  to = "/add-note.html"
  status = 200
  force = true

[[redirects]]
  from = "/notes"
  to = "/notes.html"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
